FROM python:3.8

WORKDIR /model_server

# Install cron
RUN apt-get update && apt-get install -y cron


COPY ./model_server/requirements.txt /model_server/

RUN pip install huggingface_hub --upgrade
RUN pip install --no-cache-dir -r requirements.txt

COPY . /model_server/

# Add crontab file in the cron directory
ADD crontab /etc/cron.d/my-crontab

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/my-crontab

# Apply cron job
RUN crontab /etc/cron.d/my-crontab

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Run the command on container startup
CMD cron && tail -f /var/log/cron.log