FROM python:3.8

WORKDIR /model_server

COPY ./model_server/requirements.txt /model_server/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /model_server/

CMD ["uvicorn", "model_server:app", "--host", "0.0.0.0", "--port", "8000"]
